import {
  IsBoolean,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';

/**
 * message:send payload.
 *
 * The `clientId` is generated by the sender's device and echoed back in both the
 * acknowledgement and the broadcast. That is what lets a bubble rendered
 * optimistically be matched to its confirmed row instead of appearing twice — the
 * client finds its own placeholder by `clientId`, and messages from the sender's
 * other devices arrive as new rows with ids it has never seen.
 *
 * The global `ValidationPipe` applies to websocket handlers as well as HTTP, so
 * this validation runs identically on both transports.
 */
export class SendMessageDto {
  @IsUUID(undefined, { message: 'conversationId must be a valid UUID' })
  conversationId: string;

  /**
   * Device-generated id for this specific send attempt.
   *
   * A v4 UUID: the only requirement is that one device does not repeat a value
   * within a thread, and v4 gives that without coordination. This is
   * deliberately *not* the server's `uuid(7)` — the ordering there is for the
   * message row, not for the send.
   */
  @IsUUID('4', { message: 'clientId must be a v4 UUID' })
  clientId: string;

  @IsString()
  @MinLength(1, { message: 'Message cannot be empty' })
  @MaxLength(2000, { message: 'Message is too long (2000 characters max)' })
  content: string;
}

/** conversation:subscribe / conversation:unsubscribe payload. */
export class SubscribeConversationDto {
  @IsUUID(undefined, { message: 'conversationId must be a valid UUID' })
  conversationId: string;
}

/** message:read payload. */
export class MarkReadDto {
  @IsUUID(undefined, { message: 'conversationId must be a valid UUID' })
  conversationId: string;
}

/**
 * typing:state payload.
 *
 * A keystroke-rate event, so everything it needs must already be on the socket:
 * there is no row to read and nothing to write. `typing` is a real boolean
 * rather than a flag convention — the pipe runs without coercion, so `IsBoolean`
 * rejects the string `"true"` instead of silently treating it as typing.
 */
export class TypingDto {
  @IsUUID(undefined, { message: 'conversationId must be a valid UUID' })
  conversationId: string;

  @IsBoolean()
  typing: boolean;
}